eventproject/eventproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('members/',include('members.urls')),
] + static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eventproject/main/urls.py
from django.urls import path
from .import views

app_name="main"

urlpatterns = [
    path('' , views.home_page , name='home_page'),
    path('events/' , views.all_events , name='list-events'),
    path('add_venue' , views.add_venue , name='add_venue'),
    path('list_venues' , views.list_venues , name='list-venues'),
    path('show_venue/<venue_id>' , views.show_venue , name='show-venue'),
    path('show_event/<event_id>' , views.show_event , name='show-event'),
    path('update_venue/<venue_id>' , views.update_venue , name='update-venue'),
    path('update_event/<event_id>' , views.update_event , name='update-event'),
    path('add_event' , views.add_event , name='add-event'),
    path('delete_event/<event_id>' , views.delete_event , name='delete-event'),
    path('delete_venue/<venue_id>' , views.delete_venue , name='delete-venue'),
    path("review/venue/add/<venue_id>/", views.add_review, name="add_review"),
    path("review/event/add/<event_id>/", views.add_review_evevnt, name="add_review_event"),
]

eventproject/members/urls.py
from django.urls import path
from .import views

app_name="account"


urlpatterns = [
    
    path('login_user/',views.login_user, name="login"),
    path('logout_user/',views.logout_user, name="logout"),
    path('register/',views.register_user, name="register"),
]

eventproject/main/models.py
from django.db import models
from django.contrib.auth.models import User

class Venue(models.Model):
    name = models.CharField('venue name' , max_length=120)
    addrise = models.CharField('address ',max_length=120)
    phone = models.CharField('phone' ,blank=True, max_length=20)
    email_addriss = models.EmailField('email' , blank=True, max_length=60)
    websit = models.URLField('web site' , blank=True , max_length=120)
    venue_image = models.ImageField(null=True, blank=True, upload_to="images/")
    


    def __str__(self):
        return self.name



class EventUser(models.Model):
    firstName= models.CharField(max_length=120)
    lastName = models.CharField(max_length=120)
    email = models.EmailField('email', max_length=120)

    def __str__(self):
        return self.firstName + ' ' +self.lastName

class Event(models.Model):
    name = models.CharField('event name' , max_length=120)
    event_date = models.DateTimeField('event date' ,)
    # venue = models.CharField('venue' , max_length=120)
    venue = models.CharField('veune name' , max_length=120)    #--------------------edit venue to venue_location
    manager = models.ForeignKey(User , blank=True , null=True , on_delete=models.SET_NULL)
    Description = models.TextField(blank=True)
    event_image = models.ImageField(null=True, blank=True, upload_to="images/")

    def __str__(self):
        return self.name

class Review(models.Model):

    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    rating =  models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return f"{self.user} : {self.venue}"

class Review_Event(models.Model):

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    rating =  models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return f"{self.user} : {self.event}"


# Create your models here.

eventproject/main/views.py
from django.shortcuts import render, redirect
from datetime import date,time,datetime
from .models import Event , Venue, Review, Review_Event
from django.http import HttpRequest,HttpResponseRedirect, HttpResponse


def home_page(request: HttpRequest):
    
    return render(request , 'main/base.html')


def all_events(request: HttpRequest):
    event_list = Event.objects.all().order_by('event_date')
    return render(request , 'main/event_list.html' , {'event_list': event_list})

def add_venue(request: HttpRequest):
    if request.user.is_staff:
        if request.method == "POST":
            new_venue = Venue(
                name= request.POST["name"],
                addrise = request.POST["addrise"],
                phone = request.POST["phone"], 
                email_addriss=request.POST["email"],
                websit = request.POST["websit"],
                venue_image = request.FILES["venue_image"])
            new_venue.save()
            return redirect('main:home_page')

        return render(request , "main/add_venue.html")
    return redirect('account:login')


def list_venues(request: HttpRequest):
    
        venue_list = Venue.objects.all().order_by('name')
        return render(request, 'main/venue.html',{"venue_list":venue_list})






def update_venue(request: HttpRequest, venue_id):
    venue = Venue.objects.get(pk=venue_id)
    if request.method == "POST":
        venue.name = request.POST["name"]
        venue.addrise = request.POST["address"]
        venue.phone = request.POST["phone"]
        venue.email_addriss = request.POST["email"]
        venue.websit = request.POST["website"]
        #to check if user chosen a file to upload for the update
        venue.save()
        return redirect("main:list-venues")
    return render(request, 'main/update_venue.html')



def update_event(request: HttpRequest, event_id):
    event = Event.objects.get(pk=event_id)
    if request.method == "POST":
        event.name = request.POST["name"]
        event.event_date = request.POST["date"]
        event.venue = request.POST["venue"]
        # event.manager = request.POST["mohammed"]
        event.manager = request.user
        event.Description = request.POST["description"]

        event.save()
        return redirect("main:list-events")
    return render(request, 'main/update_event.html')

#Delete an Event
def delete_event(request:HttpRequest, event_id):
     event = Event.objects.get(pk=event_id) 
     event.delete()
     return redirect('main:list-events')


#Delete an Venue
def delete_venue(request:HttpRequest, venue_id):
     venue = Venue.objects.get(pk=venue_id) 
     venue.delete()
     return redirect('main:list-venues')



def add_event(request : HttpRequest):


    if request.method == "POST":
        #to add a new entry
        new_event = Event(
            name= request.POST["name"],
            event_date = request.POST["date"],
            venue = request.POST["venue"], 
            manager = request.user,
            Description = request.POST["description"],
            event_image = request.FILES["event_image"])
            
        new_event.save()
        return redirect("main:list-events")


    return render(request, "main/add_event.html")




def show_venue(request:HttpRequest, venue_id):
    if request.user.is_authenticated:
        venues = Venue.objects.get(pk=venue_id)
        reviews = Review.objects.filter(venue=venues)
        return render(request, 'main/show_venue.html',{"venue":venues,"reviews":reviews})
    return redirect('account:login')    


def show_event(request : HttpRequest, event_id):
    events = Event.objects.get(pk=event_id)
    reviews = Review_Event.objects.filter(event=events)
    return render(request, 'main/show_event.html',{"event":events,"reviews":reviews})



def add_review(request : HttpRequest, venue_id):

    if request.method == "POST":
        venue = Venue.objects.get(id=venue_id)
        new_review = Review(user = request.user, venue=venue, content = request.POST["content"], rating = request.POST["rating"])
        new_review.save()

    return redirect("main:show-venue", venue_id=venue_id)


def add_review_evevnt(request : HttpRequest, event_id):

    if request.method == "POST":
        events = Event.objects.get(id=event_id)
        new_review = Review_Event(user = request.user, event=events, content = request.POST["content"], rating = request.POST["rating"])
        new_review.save()
    return redirect("main:show-event", event_id=event_id)

   

eventproject/main/templates/main/add_event.html
{% extends 'main/base.html' %}

{% block content %}

{%if user.is_staff %}
<h1 style="color: #ffff">Add Event</h1>
<br/><br/>



    <div class="container">

        <form action="" method=POST enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-floating mt-2">
                <input name="name" type="text" class="form-control"  placeholder="username">
                <label for="floatingInput">Event Name</label>
            </div> 
            <div class="form-floating mt-2">
                <input name="date" type="date" class="form-control"  placeholder="username">
                <label for="floatingInput">event_date</label>
            </div> 
            <div class="form-floating mt-2">
                <input name="venue" type="text" class="form-control"  placeholder="username">
                <label for="floatingInput">venue</label>
            </div> 

            <div class="form-floating mt-2">
                <input name="description" type="textarea" class="form-control"  placeholder="username">
                <label for="floatingInput">Description</label>
            </div>
            <div class="mt-3" style="color: #ffff">
                <label>Choose File:</label>
                <input type="file" name="event_image" class="form-control"/>
              </div>
            <br> 
            <input type="submit" value="submit" class="btn btn-success">

        </form>

    </div>
    {% endif %}
    <br/><br/>




{% endblock %}

eventproject/main/templates/main/add_venue.html
{% extends 'main/base.html' %}

{% block content %}

{%if user.is_staff %}
<h1 style="color: #ffff">Add New Venue</h1>
<br>


<div class="container">
<form class="mx-sm-3 mb-2" action="" method=POST enctype="multipart/form-data">
    
    {% csrf_token %}
    <div class="form-floating mt-2">
        <input name="name" type="text" class="form-control" >
        <label for="floatingInput">Venue Name</label>
    </div> 
    <div class="form-floating mt-2">
        <input name="addrise" type="text" class="form-control" >
        <label for="floatingInput">Address</label>
    </div> 
    <div class="form-floating mt-2">
        <input name="phone" type="phone" class="form-control"  placeholder="username">
        <label for="floatingInput">phone</label>
    </div> 
    <div class="form-floating mt-2">
        <input name="email" type="text" class="form-control" >
        <label for="floatingInput">email</label>
    </div> 
    <div class="form-floating mt-2">
        <input name="websit" type="textarea" class="form-control"  >
        <label for="floatingInput">websit</label>
    </div>  
    <div class="mt-3">
        <label style="color: #ffff">Choose File:</label>
        <input type="file" name="venue_image" class="form-control"/>
      </div>
   <br>
    <input type="submit" value="submit" class="btn btn-success">
    
</form>
</div>


{% endif %}


{% endblock %}

eventproject/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EVENT</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Changa&family=Nanum+Gothic&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link href="{% static 'css/main.css'%}" rel="stylesheet" />
 <style>




body {

background-repeat: no-repeat;
background-size: cover;
background-image: url("{% static 'img/ticket.jpg' %}"); 


}
h1.odcom {
  padding: 100px;
  border: 10px solid #47b0c7;
  margin: 80px 50px 100px 25px;
  text-align: center;
  color: azure;
  border-radius: 30px;
  padding: 60px;
  background: position 5px;
}

</style>
    
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark shadow-5-strong ">
    <div class="container-md">
      <img src="{% static 'img/Events.png' %}"style="width: 200px " alt="">
          <div class="collapse navbar-collapse p-4" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'main:home_page' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  EVENT
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'main:list-events' %}">Events</a></li>
                  {%if user.is_staff %}
                  <li><a class="dropdown-item" href="{% url 'main:add-event' %}">Add Event</a></li>
                  {% endif %}
                </ul>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  VENUE
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'main:list-venues' %}">Venues</a></li>
                  {%if user.is_staff %}
                  <li><a class="dropdown-item" href="{% url 'main:add_venue' %}">Add Venue</a>
                  {% endif %}
                </ul>
              </li>



              {%if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:register' %}">Register</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">Login</a>
              </li>
              {% endif %}
              </form>
              
            </ul>
            

          </div>
         
           
             <h4 style="color: #ffff">{{request.user.username}}</h4>
          
        </div>
      </nav>
      <div class="container ">
        <br/>
      {% block content %}
      <h1 class="odcom">Welcome To The Events Management Website</h1>
    {% endblock %}

  </div>
  
</body>
</html>

eventproject/main/templates/main/event_list.html
{% extends 'main/base.html' %}
{% block content %}

<h1 style="color: #ffff">Events</h1>

    {% for event in event_list %}
    <div class="card">
        <div class="card-header">
           <h4> {{ event }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">Venue: {{event.venue}}</h5>
            {%if user.is_staff %}
            
                <a href="{% url 'main:update-event' event.id %}"class="btn btn-outline-dark btn-sm">Update Event</a>
                <a href="{% url 'main:delete-event' event.id %}"class="btn btn-outline-danger btn-sm">Delete Event</a>
                {% endif %}
                {%if user.is_authenticated %}
                <a href="{% url 'main:show-event' event.id %}"class="btn btn-outline-success btn-sm">Show Event</a>
                <br/>
                {% endif %}
            </div>
            
        </div>
        <br/><br/>
        {% endfor %}
        
    </div>
    <br/><br/>
    
    
{% endblock %}

eventproject/main/templates/main/event_review.html
{% extends 'main/base.html' %}
{% block content %}



<div class="card">
    <div class="card-header">
        Event
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ event }}</h5>
        <p class="card-text">
         <ul>
            <li>Date: {{event.event_date}}</li>
            <li>venue website :{{event.venue.websit}}</li>
            <li>Manager :{{event.manager}}</li>
            <li>Description :{{event.Description}}</li>
           <img src="{{ event.event_image.url }}" class="w-25 h-50" />
         </ul>
        </p>
    </div>
</div>
<div  class=" mt-3">
    <h3 style="color: #ffff;">Reviews :</h3>
    {% for review in reviews  %}
    <div class="container p-2 my-2 bg-light-subtle text-black ">

            <h5>{{ review.user }}</h5>
            <h6>{{ review.rating }} Stars</h6>
            <p>{{ review.content }}</p>

        </div>
    {% endfor %}
    <br>
    
</div>

{% if request.user.is_authenticated %}
<div class="mt-3">
    <h3 style="color: #ffff">Add Review</h3>
    <div>
        <form action="{% url  'main:add_review' venue.id %}" method="post">
            {% csrf_token %} 

            <textarea name="content" class="form-control mt-3" placeholder="Your Review here..."></textarea>
            <div class="mt-3">
                <h4 style="color: #ffff;">Rating:</h4>
                <div class="rating">
                    <input id="rating1" type="radio" name="rating" value="1">
                    <label for="rating1">1</label>
                    <input id="rating2" type="radio" name="rating" value="2">
                    <label for="rating2">2</label>
                    <input id="rating3" type="radio" name="rating" value="3">
                    <label for="rating3">3</label>
                    <input id="rating4" type="radio" name="rating" value="4">
                    <label for="rating4">4</label>
                    <input id="rating5" type="radio" name="rating" value="5">
                    <label for="rating5">5</label>
                </div>
            </div>
            <input class="btn btn-primary mt-2" type="submit" value="Add Review" />

        </form>
    </div>
</div>

{% endif %}

{% endblock %}

eventproject/main/templates/main/show_event.html
{% extends 'main/base.html' %}
{% block content %}



<div class="card">
    <div class="card-header">
        {{ event }}
    </div>

    <div class="card-body">
        <h5 class="card-title">Venue: {{event.venue}}</h5>
         <p class="card-text">
            <div class="row">
                <div class="col">
                    <ul>
                        <li>Date: {{event.event_date}}</li>
                        <li>Manager :{{event.manager}}</li>
                        <li>Description :{{event.Description}}</li>  
                    </ul>
                </div>
                <div class="col">
                    <img  style=" height: 200px; width: 350px; " src="{{ event.event_image.url }}" class="rounded float-end" alt="...">
                    <img src="" class="w-100" />
                </div>
            </div>

         </p>
    </div>





</div>
<div  class=" mt-3">
    <h3 style="color: #ffff;">Reviews :</h3>
    {% for review in reviews  %}
    <div class="container p-2 my-2 bg-light-subtle text-black ">

            <h5>{{ review.user }}</h5>
            <h6>{{ review.rating }} Stars</h6>
            <p>{{ review.content }}</p>

        </div>
    {% endfor %}
    <br>
    
</div>

{% if request.user.is_authenticated %}
<div class="mt-3">
    <h3 style="color: #ffff">Add Review</h3>
    <div>
        <form action="{% url  'main:add_review_event' event.id %}" method="post">
            {% csrf_token %} 

            <textarea name="content" class="form-control mt-3" placeholder="Your Review here..."></textarea>
            <div class="mt-3">
                <h4 style="color: #ffff;">Rating:</h4>
                <div class="rating">
                    <input id="rating1" type="radio" name="rating" value="1">
                    <label for="rating1">1</label>
                    <input id="rating2" type="radio" name="rating" value="2">
                    <label for="rating2">2</label>
                    <input id="rating3" type="radio" name="rating" value="3">
                    <label for="rating3">3</label>
                    <input id="rating4" type="radio" name="rating" value="4">
                    <label for="rating4">4</label>
                    <input id="rating5" type="radio" name="rating" value="5">
                    <label for="rating5">5</label>
                </div>
            </div>
            <input class="btn btn-primary mt-2" type="submit" value="Add Review" />

        </form>
    </div>

</div>


{% endif %}

{% endblock %}

eventproject/main/templates/main/show_venue.html
{% extends 'main/base.html' %}
{% block content %}


<div class="card">
    <div class="card-header">
        <h3>Venue</h3>
    </div>

    <div class="card-body">
        <h5 class="card-title">{{ venue }}</h5>
        <p class="card-text">
            <div class="row">
                <div class="col">
                    <ul>
                        <li>Address: {{ venue.addrise}}</li>
                        <li>Phone: {{ venue.phone }}</li>
                        <li>Email: {{ venue.email_addriss }}</li>
                        <li>Website: <a href="{{ venue.websit }}">{{ venue.websit }}</a></li><br>
                    </ul>
                </div>
                <div class="col">
                    <img  style=" height: 200px; width: 350px; " src="{{ venue.venue_image.url }}" class="rounded float-end" alt="...">
                </div>
            </div>
        </p>
    </div>
</div>


<div  class=" mt-3">
    <h3 style="color: #ffff;">Reviews :</h3>
    {% for review in reviews  %}
    <div class="container p-2 my-2 bg-light-subtle text-black ">

            <h5>{{ review.user }}</h5>
            <h6>{{ review.rating }} Stars</h6>
            <p>{{ review.content }}</p>

        </div>
    {% endfor %}
    <br>
    
</div>

{% if request.user.is_authenticated %}
<div class="mt-3">
    <h3 style="color: #ffff">Add Review</h3>
    <div>
        <form action="{% url  'main:add_review' venue.id %}" method="post">
            {% csrf_token %} 

            <textarea name="content" class="form-control mt-3" placeholder="Your Review here..."></textarea>
            <div class="mt-3">
                <h4 style="color: #ffff;">Rating:</h4>
                <div class="rating">
                    <input  id="rating1" type="radio" name="rating" value="1">
                    <label for="rating1">1</label>
                    <input id="rating2" type="radio" name="rating" value="2">
                    <label for="rating2">2</label>
                    <input id="rating3" type="radio" name="rating" value="3">
                    <label for="rating3">3</label>
                    <input id="rating4" type="radio" name="rating" value="4">
                    <label for="rating4">4</label>
                    <input id="rating5" type="radio" name="rating" value="5">
                    <label for="rating5">5</label>
                </div>
            </div>
            <input class="btn btn-primary mt-2" type="submit" value="Add Review" />

        </form>
        <br>
    </div>
    {% else %}

</div>
<div class="border p-3 mt-3 " style="color: #ffff">
    <p>To add reveiew please <a href="{% url 'account:login'%}">Sing In</a> or <a href="{% url 'account:register'%}">Sign Up</a></p>
</div>


{% endif %}

{% endblock %}

eventproject/main/templates/main/update_event.html
{% extends 'main/base.html' %}
{% block content %}
{%if user.is_staff %}

    <h1 style="color: rgba(255, 255, 255, 0.889)">Update Event...</h1>
    <br>
      <form action="" method="POST" enctype="multipart/form-data" style="color: #ffff">
          {% csrf_token %}
      
          <div class="mt-3">
            <label class="form-label">Event Name</label>
            <input type="text" name="name" class="form-control"  />
          </div>
      
          <div class="mt-3">
            <label class="form-label">Date</label>
            <input type="date" name="date" class="form-control"  />
          </div>
      
          <div class="mt-3">
            <label class="form-label">venue</label>
            <input type="text" name="venue" class="form-control"  />
          </div>
      
        
          <div class="mt-3">
            <label class="form-label">description</label>
            <textarea name="description" class="form-control"></textarea>
          </div>
    
          <br>
            <input type="submit" class="btn btn-primary" value="Update Event" />
      
          
      
      </form><br>
      
    </div>


{% endif %}
    
   

{% endblock %}

eventproject/main/templates/main/update_venue.html
{% extends 'main/base.html' %}
{% block content %}
{%if user.is_staff %}

<div class="container">
    <h2 style="color: #ffff">Update Venue . .</h2>
    
    <form action="" method="POST" enctype="multipart/form-data" style="color: #ffff">
        {% csrf_token %}
    
        <div class="mt-3">  
          <label class="form-label">Venue Name</label>
          <input type="text" name="name" class="form-control"  />
        </div>
    
        <div class="mt-3">
          <label class="form-label">Date</label>
          <input type="date" name="address" class="form-control"  />
        </div>
    
        <div class="mt-3">
          <label class="form-label">Phone</label>
          <input type="text" name="phone" class="form-control"  />
        </div>
    
        <div class="mt-3">
          <label class="form-label">Email</label>
          <input type="email" name="email" class="form-control">
        </div>
        <div class="mt-3">
            <label class="form-label">Web</label>
            <input type="text" name="website" class="form-control">
          
        </div>
        <br>
     <input type="submit" class="btn btn-primary" value="Update Venue" />
    
        
    
    </form><br>
    
    </div>
    
    {% endif %}
    
   

{% endblock %}

eventproject/main/templates/main/venue.html
{% extends 'main/base.html' %}
{% block content %}
<style>
    h1{
        color: rgb(247, 247, 247);
    }
</style>

<h1>Venues..</h1>
<br/>

{% for venue in venue_list %}
<div class="card">
    <div class="card-header">
       <h4> {{ venue }}</h4>
    </div>
    <div class="card-body">
        {%if user.is_staff %}
            <a href="{% url 'main:update-venue' venue.id %}"class="btn btn-outline-dark btn-sm">Update</a>
            <a href="{% url 'main:delete-venue' venue.id %}"class="btn btn-outline-danger btn-sm">Delete</a>
            {% endif %}
           
            <a href="{% url 'main:show-venue' venue.id %}" class="btn btn-outline-primary btn-sm">Show Venue</a>
            <br/>
            
        </div>
        
    </div>
    <br/><br/>
   
    {% endfor %}
</div>

{% endblock %}